/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 02 04:40:15 GMT 2019
 */

package als.pbt.lab11;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import als.pbt.lab11.MonthsOnAndAfter;
import java.util.InputMismatchException;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MonthsOnAndAfter_ESTest extends MonthsOnAndAfter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SystemInUtil.addInputLine("m9?p,0`ew=vI{%?/");
      String[] stringArray0 = new String[1];
      // Undeclared exception!
      try { 
        MonthsOnAndAfter.main(stringArray0);
        fail("Expecting exception: InputMismatchException");
      
      } catch(InputMismatchException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      MonthsOnAndAfter.printMonthsOnAndAfter(6);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      MonthsOnAndAfter.printMonthsOnAndAfter((-4985));
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      MonthsOnAndAfter.printMonthsOnAndAfter(11);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      MonthsOnAndAfter.printMonthsOnAndAfter(10);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      MonthsOnAndAfter.printMonthsOnAndAfter(9);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      MonthsOnAndAfter.printMonthsOnAndAfter(8);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      MonthsOnAndAfter.printMonthsOnAndAfter(7);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SystemInUtil.addInputLine("6");
      String[] stringArray0 = new String[1];
      MonthsOnAndAfter.main(stringArray0);
      assertEquals(1, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      MonthsOnAndAfter.printMonthsOnAndAfter(5);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      MonthsOnAndAfter.printMonthsOnAndAfter(4);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      MonthsOnAndAfter.printMonthsOnAndAfter(3);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      MonthsOnAndAfter.printMonthsOnAndAfter(2);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      MonthsOnAndAfter.printMonthsOnAndAfter(1);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      MonthsOnAndAfter.printMonthsOnAndAfter(0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      MonthsOnAndAfter monthsOnAndAfter0 = new MonthsOnAndAfter();
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      // Undeclared exception!
      try { 
        MonthsOnAndAfter.main((String[]) null);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }
}
