/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 02 05:01:38 GMT 2019
 */

package als.pbt.lab13;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import als.pbt.lab13.OperationsBetween;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class OperationsBetween_ESTest extends OperationsBetween_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      OperationsBetween operationsBetween0 = new OperationsBetween((-2554), 0);
      operationsBetween0.product();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      OperationsBetween operationsBetween0 = new OperationsBetween((-248), 4385);
      int int0 = operationsBetween0.sum();
      assertEquals(9585429, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String[] stringArray0 = new String[22];
      stringArray0[0] = "7";
      stringArray0[1] = "7";
      OperationsBetween.main(stringArray0);
      assertEquals(22, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      OperationsBetween operationsBetween0 = new OperationsBetween((-1207), (-1207));
      int int0 = operationsBetween0.sum();
      assertEquals((-1207), int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      OperationsBetween operationsBetween0 = new OperationsBetween((-1729), (-1729));
      int int0 = operationsBetween0.product();
      assertEquals((-1729), int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      // Undeclared exception!
      try { 
        OperationsBetween.main((String[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("als.pbt.lab13.OperationsBetween", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      String[] stringArray0 = new String[0];
      // Undeclared exception!
      try { 
        OperationsBetween.main(stringArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("als.pbt.lab13.OperationsBetween", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      OperationsBetween operationsBetween0 = new OperationsBetween(441, 3);
      int int0 = operationsBetween0.product();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      OperationsBetween operationsBetween0 = new OperationsBetween(0, (-2361));
      int int0 = operationsBetween0.sum();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      String[] stringArray0 = new String[2];
      // Undeclared exception!
      try { 
        OperationsBetween.main(stringArray0);
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // null
         //
         verifyException("java.lang.Integer", e);
      }
  }
}
