/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 02 05:06:19 GMT 2019
 */

package als.pbt.lab9;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import als.pbt.lab9.CompareNums;
import java.util.InputMismatchException;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CompareNums_ESTest extends CompareNums_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SystemInUtil.addInputLine("3");
      SystemInUtil.addInputLine("4");
      CompareNums.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[5];
      SystemInUtil.addInputLine("Enter first integer: ");
      // Undeclared exception!
      try { 
        CompareNums.main(stringArray0);
        fail("Expecting exception: InputMismatchException");
      
      } catch(InputMismatchException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String string0 = CompareNums.comparison(1, 1);
      assertEquals("equal to", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String string0 = CompareNums.comparison(3599, 1678);
      assertEquals("greater than", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      String string0 = CompareNums.comparison(1678, 3599);
      assertEquals("less than", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      CompareNums compareNums0 = new CompareNums();
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      String[] stringArray0 = new String[5];
      // Undeclared exception!
      try { 
        CompareNums.main(stringArray0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }
}
