/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 02 04:48:30 GMT 2019
 */

package als.pbt.lab9;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import als.pbt.lab9.LetterGrade;
import java.util.InputMismatchException;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LetterGrade_ESTest extends LetterGrade_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      String string0 = LetterGrade.letterGrade(52.5);
      assertEquals("D", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      String string0 = LetterGrade.letterGrade(66.5);
      assertEquals("D+", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      String string0 = LetterGrade.letterGrade(69.5);
      assertEquals("C-", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      String string0 = LetterGrade.letterGrade(72.5);
      assertEquals("C", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      String string0 = LetterGrade.letterGrade(78.0100410639917);
      assertEquals("C+", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      String string0 = LetterGrade.letterGrade(80.0);
      assertEquals("B-", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      String string0 = LetterGrade.letterGrade(85.89813821641633);
      assertEquals("B", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      String string0 = LetterGrade.letterGrade(87.8347258461727);
      assertEquals("B+", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      String string0 = LetterGrade.letterGrade(89.5);
      assertEquals("A-", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      String string0 = LetterGrade.letterGrade(92.5);
      assertEquals("A", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SystemInUtil.addInputLine("3");
      LetterGrade.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      String[] stringArray0 = new String[4];
      SystemInUtil.addInputLine("B-");
      // Undeclared exception!
      try { 
        LetterGrade.main(stringArray0);
        fail("Expecting exception: InputMismatchException");
      
      } catch(InputMismatchException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      String string0 = LetterGrade.letterGrade((-120.521206802));
      assertEquals("F", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      String string0 = LetterGrade.letterGrade(67.31856837841617);
      assertEquals("D+", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      String string0 = LetterGrade.letterGrade(72.0);
      assertEquals("C-", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      String string0 = LetterGrade.letterGrade(73.74001613740616);
      assertEquals("C", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      String string0 = LetterGrade.letterGrade(76.5);
      assertEquals("C+", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      String string0 = LetterGrade.letterGrade(64.346129);
      assertEquals("D", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      String string0 = LetterGrade.letterGrade(82.5);
      assertEquals("B", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      String string0 = LetterGrade.letterGrade(86.5);
      assertEquals("B+", string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      String string0 = LetterGrade.letterGrade(89.86620644);
      assertEquals("A-", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      String string0 = LetterGrade.letterGrade(94.12569859665888);
      assertEquals("A", string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      String string0 = LetterGrade.letterGrade(79.5);
      assertEquals("B-", string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      LetterGrade letterGrade0 = new LetterGrade();
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      String[] stringArray0 = new String[9];
      // Undeclared exception!
      try { 
        LetterGrade.main(stringArray0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }
}
