/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 02 05:21:14 GMT 2019
 */

package als.pbt.lab5;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import als.pbt.lab5.CompoundInterestMethod;
import java.util.InputMismatchException;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CompoundInterestMethod_ESTest extends CompoundInterestMethod_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      double double0 = CompoundInterestMethod.compoundInterest(1L, 1L, (-1855), 1);
      assertEquals(2.719014881231709, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SystemInUtil.addInputLine("2");
      SystemInUtil.addInputLine("2");
      SystemInUtil.addInputLine("2");
      SystemInUtil.addInputLine("2");
      String[] stringArray0 = new String[1];
      CompoundInterestMethod.main(stringArray0);
      assertEquals(1, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SystemInUtil.addInputLine("2");
      SystemInUtil.addInputLine("2");
      SystemInUtil.addInputLine("2");
      String[] stringArray0 = new String[1];
      // Undeclared exception!
      try { 
        CompoundInterestMethod.main(stringArray0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      double double0 = CompoundInterestMethod.compoundInterest((-1504L), (-1504L), 0, 0);
      assertEquals((-1504.0), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      String[] stringArray0 = new String[9];
      SystemInUtil.addInputLine("{Y");
      // Undeclared exception!
      try { 
        CompoundInterestMethod.main(stringArray0);
        fail("Expecting exception: InputMismatchException");
      
      } catch(InputMismatchException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      CompoundInterestMethod compoundInterestMethod0 = new CompoundInterestMethod();
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      double double0 = CompoundInterestMethod.compoundInterest(1129L, 1129L, (-2760), (-2760));
      assertEquals(0.0, double0, 0.01);
  }
}
