/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 02 05:19:37 GMT 2019
 */

package als.pbt.lab5;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import als.pbt.lab5.DegreeConversionMethod;
import java.util.InputMismatchException;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DegreeConversionMethod_ESTest extends DegreeConversionMethod_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      double double0 = DegreeConversionMethod.convert((-53.8));
      assertEquals((-64.84), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[0];
      // Undeclared exception!
      try { 
        DegreeConversionMethod.main(stringArray0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SystemInUtil.addInputLine("S'w?j*.qq+(j6");
      String[] stringArray0 = new String[2];
      // Undeclared exception!
      try { 
        DegreeConversionMethod.main(stringArray0);
        fail("Expecting exception: InputMismatchException");
      
      } catch(InputMismatchException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      double double0 = DegreeConversionMethod.convert(0.0);
      assertEquals(32.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SystemInUtil.addInputLine("2 (Q;E4H3");
      DegreeConversionMethod.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      DegreeConversionMethod degreeConversionMethod0 = new DegreeConversionMethod();
  }
}
