/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 02 05:14:52 GMT 2019
 */

package als.pbt.lab5;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import als.pbt.lab5.PerimeterCalculationMethod;
import java.util.InputMismatchException;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PerimeterCalculationMethod_ESTest extends PerimeterCalculationMethod_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int int0 = PerimeterCalculationMethod.calculatePerimeter(0, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int int0 = PerimeterCalculationMethod.calculatePerimeter((-5897), (-5897));
      assertEquals((-23588), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String[] stringArray0 = new String[7];
      SystemInUtil.addInputLine("=! 5X\"");
      // Undeclared exception!
      try { 
        PerimeterCalculationMethod.main(stringArray0);
        fail("Expecting exception: InputMismatchException");
      
      } catch(InputMismatchException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      int int0 = PerimeterCalculationMethod.calculatePerimeter(769, 769);
      assertEquals(3076, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SystemInUtil.addInputLine("0");
      String[] stringArray0 = new String[11];
      SystemInUtil.addInputLine("9");
      PerimeterCalculationMethod.main(stringArray0);
      assertEquals(11, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      String[] stringArray0 = new String[7];
      // Undeclared exception!
      try { 
        PerimeterCalculationMethod.main(stringArray0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      PerimeterCalculationMethod perimeterCalculationMethod0 = new PerimeterCalculationMethod();
  }
}
