/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 02 05:13:18 GMT 2019
 */

package als.pbt.lab6;

import org.junit.Test;
import static org.junit.Assert.*;
import als.pbt.lab6.PrintInt;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PrintInt_ESTest extends PrintInt_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PrintInt.printInt(2478);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PrintInt printInt0 = new PrintInt();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String[] stringArray0 = new String[4];
      PrintInt.main(stringArray0);
      assertEquals(4, stringArray0.length);
  }
}
