/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 02 05:10:12 GMT 2019
 */

package als.pbt.lab6;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import als.pbt.lab6.TwoDoubles;
import als.pbt.lab6.TwoOperations;
import java.util.InputMismatchException;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TwoOperations_ESTest extends TwoOperations_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[1];
      SystemInUtil.addInputLine("3");
      SystemInUtil.addInputLine("3");
      TwoOperations.main(stringArray0);
      assertEquals(1, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[0];
      // Undeclared exception!
      try { 
        TwoOperations.main(stringArray0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String[] stringArray0 = new String[8];
      SystemInUtil.addInputLine("^$p#@ X(&4bM,s");
      // Undeclared exception!
      try { 
        TwoOperations.main(stringArray0);
        fail("Expecting exception: InputMismatchException");
      
      } catch(InputMismatchException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TwoDoubles twoDoubles0 = TwoOperations.subAdd(0.0, 0.0);
      assertNotNull(twoDoubles0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SystemInUtil.addInputLine("8");
      String[] stringArray0 = new String[8];
      SystemInUtil.addInputLine("0");
      TwoOperations.main(stringArray0);
      assertEquals(8, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      TwoDoubles twoDoubles0 = TwoOperations.multDiv(0.0, 0.0);
      assertNotNull(twoDoubles0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      TwoOperations twoOperations0 = new TwoOperations();
  }
}
