/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 02 05:03:05 GMT 2019
 */

package als.pbt.lab10;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import als.pbt.lab10.InRange;
import java.util.InputMismatchException;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class InRange_ESTest extends InRange_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SystemInUtil.addInputLine("2");
      SystemInUtil.addInputLine("12");
      SystemInUtil.addInputLine("12");
      String[] stringArray0 = new String[6];
      InRange.main(stringArray0);
      assertEquals(6, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      InRange inRange0 = new InRange((-1922), 463);
      boolean boolean0 = inRange0.outOfRange(0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      InRange inRange0 = new InRange((-2658), (-2658));
      boolean boolean0 = inRange0.inRange((-2658));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String[] stringArray0 = new String[24];
      SystemInUtil.addInputLine("Number: ");
      // Undeclared exception!
      try { 
        InRange.main(stringArray0);
        fail("Expecting exception: InputMismatchException");
      
      } catch(InputMismatchException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SystemInUtil.addInputLine("2");
      SystemInUtil.addInputLine("2");
      SystemInUtil.addInputLine("12");
      String[] stringArray0 = new String[6];
      InRange.main(stringArray0);
      assertEquals(6, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      InRange inRange0 = new InRange(61, 61);
      boolean boolean0 = inRange0.outOfRange((-669));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      String[] stringArray0 = new String[0];
      // Undeclared exception!
      try { 
        InRange.main(stringArray0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      InRange inRange0 = new InRange((-30), (-343));
      boolean boolean0 = inRange0.inRange((-30));
      assertFalse(boolean0);
  }
}
