/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 02 04:57:51 GMT 2019
 */

package als.pbt.lab10;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import als.pbt.lab10.ScoreDice;
import java.util.InputMismatchException;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ScoreDice_ESTest extends ScoreDice_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      int int0 = ScoreDice.scoreWithNumbers(6, 10);
      assertEquals(6, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SystemInUtil.addInputLine("2");
      String[] stringArray0 = new String[4];
      ScoreDice.main(stringArray0);
      assertEquals(4, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SystemInUtil.addInputLine("als.pbt.lab10.ScoreDice");
      String[] stringArray0 = new String[7];
      // Undeclared exception!
      try { 
        ScoreDice.main(stringArray0);
        fail("Expecting exception: InputMismatchException");
      
      } catch(InputMismatchException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      int int0 = ScoreDice.scoreWithNumbers(1, 1);
      assertEquals(10, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ScoreDice scoreDice0 = new ScoreDice(32L);
      int int0 = scoreDice0.rollD6();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      int int0 = ScoreDice.scoreWithNumbers(10, 10);
      assertEquals(8, int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      int int0 = ScoreDice.scoreWithNumbers(6, (-4037));
      assertEquals((-4037), int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      int int0 = ScoreDice.scoreWithNumbers(6, 6);
      assertEquals(10, int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      int int0 = ScoreDice.scoreWithNumbers(1, 10);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      int int0 = ScoreDice.scoreWithNumbers(791, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      String[] stringArray0 = new String[10];
      // Undeclared exception!
      try { 
        ScoreDice.main(stringArray0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ScoreDice scoreDice0 = new ScoreDice((-125));
      int int0 = scoreDice0.score();
      assertEquals(10, int0);
  }
}
