/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 02 05:12:34 GMT 2019
 */

package als.pbt.lab4;

import org.junit.Test;
import static org.junit.Assert.*;
import als.pbt.lab4.GreetingMethod;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GreetingMethod_ESTest extends GreetingMethod_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GreetingMethod.printGreeting();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GreetingMethod greetingMethod0 = new GreetingMethod();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String[] stringArray0 = new String[3];
      GreetingMethod.main(stringArray0);
      assertEquals(3, stringArray0.length);
  }
}
