/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 02 05:09:19 GMT 2019
 */

package als.pbt.lab2;

import org.junit.Test;
import static org.junit.Assert.*;
import als.pbt.lab2.SquawkParrot;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SquawkParrot_ESTest extends SquawkParrot_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[5];
      SystemInUtil.addInputLine("R");
      SquawkParrot.main(stringArray0);
      assertEquals(5, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[4];
      SquawkParrot.main(stringArray0);
      assertEquals(4, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SquawkParrot squawkParrot0 = new SquawkParrot();
  }
}
